version: '2'
services:

  # DATABASE
  mysql:
    image: mariadb:latest
    command: --max_allowed_packet=256M
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated
    ports:
       - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: maindb
      MYSQL_USER: main
      MYSQL_PASSWORD: password
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: maindb
      POSTGRESQL_USER: main
      POSTGRESQL_PASSWORD: password
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: main
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./data/mongod:/data/db
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=password
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/bitnami/redis/data

  # WEBSERVER
  litespeed:
    image: litespeedtech/openlitespeed:latest
    volumes:
        - ./lsws/conf:/usr/local/lsws/conf
        - ./lsws/admin-conf:/usr/local/lsws/admin/conf
        - ./bin/container:/usr/local/bin
        - ./lsws/sites:/var/www/vhosts/
        - ./lsws/acme:/root/.acme.sh/
        - ./lsws/logs:/usr/local/lsws/logs/
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 7080:7080
    restart: always
    environment:
      DOMAIN: localhost
      TZ: Asia/Jakarta

  # PHPMYADMIN
  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    ports:
      - 8080:80
      - 8443:443
    environment:
      DOMAIN: localhost
      DATABASE_HOST: mysql
  phppgadmin:
    image: bitnami/phppgadmin:latest
    ports:
      - 8081:8080
      - 8444:443
    depends_on:
      - postgresql